version: '3.8'

services:

  frontend:
    build: ./frontend
    container_name: supermarket_frontend
    restart: always

  backend:
    build: ./backend
    container_name: supermarket_backend
    restart: always

  nginx:
    image: nginx:latest
    container_name: supermarket_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: always