name: Deploy Supermarket App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: CI/CD Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v4

      - name: Deploy Application to EC2 Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ 65.2.183.56 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Connected to EC2 Server"

            cd /home/ubuntu/supermarket-devops-project

            echo "Pulling latest code from GitHub..."
            git pull origin main

            echo "Stopping old containers..."
            docker-compose down

            echo "Building and starting new containers..."
            docker-compose up -d --build

            echo "Cleaning unused Docker images..."
            docker system prune -f

            echo "Deployment completed successfully 🚀"